### PR TITLE
Completed technical test for Teradici

### PR DESCRIPTION
**Pull request by cfeldstein**

### CODE REVIEW

**Comment by zhimoud** [comment]
This is not what the instruction said, please read again [here](https://github.com/zhimoud/rock-paper-scisors/blob/master/README.md).

**Comment by zhimoud** [comment]
Just to be clear here, fork this repo and do all changes into your repo. We need to keep this repo clean.
Thanks

**Comment by cfeldstein** [comment]
@zhimoud --> This is a pull request created from my fork, master branch onto your fork master branch. 
I just realized that I didn't grant you access to my private repo. 

image

**Comment by cfeldstein** [comment]
@zhimoud --> I pushed my local changes directly to github.com/cfeldstein/rock-paper-scissors. Did you want to see the pull request as a merge into my repo's master? Following your instructions, it does create a pull request to merge my master onto your repo's master. Perhaps now that you can view my repo you should just reject the pull request and review the code from the fork.

**Comment by zhimoud** [comment]
@cfeldstein, yes you need a PR  before changing your master branch. I will close this PR as it's needed anymore.

**Pull request closed without merging**
